### PR TITLE
Update README to reflect rsync, org-wide webhook

### PR DESCRIPTION
**Pull request by mbland**
cc: @afeld @wslack @arowla

### CODE REVIEW

**Comment by wslack** [comment]
there's something to edit in guides template as well, right?

**Comment by mbland** [comment]
18F/guides-template#61 is still open, yes.

**Comment by wslack** [comment]
Oh duh. I say merge them together! @afeld or @arowla, anything to add?

**Comment by afeld** [comment]
:+1: 

The README is getting a bit large, and the audiences are different enough that it may make sense to start splitting it up to separate Markdown files. Just a thought!

**Comment by wslack** [comment]
Merged the other PR as well.

**Pull request merged**
