### PR TITLE
Reorganize homepage in a more user-centered way

### PR DESCRIPTION
**Pull request by brittag**

### CODE REVIEW

**Comment by mbland** [comment]
So the publishing failed: https://pages.18f.gov/pages/build.log

I'm pretty sure this is config-related. @jbarnicle or @afeld, can you see if `/usr/local/18f/pages/config/pages-config.json` matches:
https://github.com/18F/knowledge-sharing-toolkit/blob/master/pages/config/pages-config.json

Also, I noticed nothing's been syncing to s3. Guess that was disabled when my credentials expired?

**Comment by jbarnicle** [comment]
looks the same to me:

```
{
  "port":             5000,
  "home":             "/usr/local/18f/pages",
  "git":              "/usr/bin/git",
  "bundler":          "/usr/local/18f/rbenv/shims/bundle",
  "bundlerCacheDir":  "bundle/cache",
  "jekyll":           "/usr/local/18f/rbenv/shims/jekyll",
  "rsync":            "/usr/bin/rsync",
  "rsyncOpts":        [
    "-vaxp",
    "--delete",
    "--ignore-errors",
    "--exclude=.[A-Za-z0-9]*"
  ],
  "payloadLimit":     1048576,
  "githubOrg":        "18F",
  "pagesConfig":      "_config_18f_pages.yml",
  "pagesYaml":        ".18f-pages.yml",
  "assetRoot":        "/guides-template",
  "fileLockWaitTime": 30000,
  "fileLockPollTime": 1000,
  "secretKeyFile":    "/usr/local/18f/pages/config/pages.secret",
  "builders": [
    {
      "branch":           "18f-pages",
      "repositoryDir":    "repos/pages.18f.gov",
      "generatedSiteDir": "sites/pages.18f.gov",
      "internalSiteDir":  "sites/pages-internal.18f.gov"
    },
    {
      "branch":           "18f-pages-staging",
      "repositoryDir":    "repos/pages-staging.18f.gov",
      "generatedSiteDir": "sites/pages-staging.18f.gov",
      "internalSiteDir":  "sites/pages-internal.18f.gov"
    },
    {
      "branch":           "18f-pages-internal",
      "repositoryDir":    "repos/pages-internal.18f.gov",
      "generatedSiteDir": "sites/pages-internal.18f.gov"
    },
    {
      "branchInUrlPattern": "v[0-9]+.[0-9]+.[0-9]*[a-z]*",
      "repositoryDir":      "repos/pages-releases.18f.gov",
      "generatedSiteDir":   "sites/pages-releases.18f.gov"
    }
  ]
}

```

**Comment by mbland** [comment]
Hmm. It must be coming from `lib/command-runner.js`, because that's the only non-test code that calls `setEncoding` on anything. Never expected it to fail, which is my dumb fault. I'll try to add some error checking and better reporting.

That said, based on the build.log file, it looks like `git clone git@github.com:18F/pages.git` is failing. Not certain why yet, but it _might_ have to do with the `stdio: inherit` option set at `https://github.com/mbland/pages-server/blob/master/lib/git-runner.js#L53`. I removed that option from the `spawn()` call used by `CommandRunner` in #44 because it was interfering with the `BuildLogger`, as I recall.

**Comment by mbland** [comment]
Good news, already able to repro in a test. PR forthcoming shortly.

**Comment by mbland** [comment]
About to send the PR, but posting the current content of https://pages2.18f.gov/pages/build.log for posterity's sake:

```
18F/pages: starting build at commit 348bbf4a5bbbd961cb822eb6b6fb6e94507dac96
description: Merge pull request #58 from 18F/homepage

Reorganize homepage in a more user-centered way
timestamp: 2016-03-18T14:10:41-04:00
committer: melody.kramer@gsa.gov
pusher: melodykramer melody.kramer@gsa.gov
sender: melodykramer
cloning pages into /usr/local/18f/pages/repos/pages.18f.gov/pages
Cannot read property 'setEncoding' of null
pages: build failed
```

**Comment by mbland** [comment]
OK, 18F/pages-server#50 is in flight. Once that's in, and a new release is pushed, pushing a new commit to this repo's `18f-pages` should behave as expected.

**Pull request merged**
